#!/usr/bin/env python3
"""#140: enforces a line-coverage floor from coverage/lcov.info (produced by
`flutter test --coverage`), so coverage can't silently regress as new code
lands without matching tests.

Excludes lib/l10n/app_localizations*.dart — generated by `flutter gen-l10n`
(gitignored, regenerated from the .arb files), not code anyone writes tests
against. Including it would make the percentage swing on translation-key
changes alone, unrelated to actual test coverage.

MIN_COVERAGE is set a few points below the coverage at the time this check
was introduced (64.82%, l10n-excluded) — a floor to catch real regressions,
not a target to chase. Raise it deliberately as coverage improves; never
lower it to make a failing PR pass.

Usage: python3 scripts/check_coverage.py [path/to/lcov.info]
"""

import sys
from pathlib import Path

MIN_COVERAGE = 60.0
EXCLUDE_SUBSTRINGS = ("lib/l10n/app_localizations",)


def compute_coverage(lcov_path: Path) -> tuple[int, int]:
    hit_lines = 0
    total_lines = 0
    skip = False
    with lcov_path.open() as f:
        for line in f:
            if line.startswith("SF:"):
                skip = any(s in line for s in EXCLUDE_SUBSTRINGS)
            elif line.startswith("DA:") and not skip:
                _, count = line[3:].strip().split(",")
                total_lines += 1
                if int(count) > 0:
                    hit_lines += 1
    return hit_lines, total_lines


def main() -> int:
    lcov_path = Path(sys.argv[1] if len(sys.argv) > 1 else "coverage/lcov.info")
    if not lcov_path.exists():
        print(f"error: {lcov_path} not found — run `flutter test --coverage` first")
        return 1

    hit, total = compute_coverage(lcov_path)
    if total == 0:
        print("error: lcov.info has no instrumented lines")
        return 1

    pct = 100 * hit / total
    print(f"Line coverage (excl. generated l10n): {hit}/{total} = {pct:.2f}%")
    print(f"Floor: {MIN_COVERAGE:.2f}%")

    if pct < MIN_COVERAGE:
        print(f"FAIL: coverage {pct:.2f}% is below the {MIN_COVERAGE:.2f}% floor")
        return 1

    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
